version: "3"

services:
  pgdb:
    image: postgres
    container_name: pgdb
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always


  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    # restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - pgdb

          

